# Generated by Django 4.1.5 on 2023-02-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_tag_remove_product_secondary_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='primary_category',
            new_name='category',
        ),
    ]
